# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_A(object):
    def setupUi(self, A):
        A.setObjectName("A")
        A.resize(284, 252)
        self.AuthWindow = QtWidgets.QWidget(A)
        self.AuthWindow.setObjectName("AuthWindow")
        self.label = QtWidgets.QLabel(self.AuthWindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.AuthWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Login_button = QtWidgets.QPushButton(self.AuthWindow)
        self.Login_button.setGeometry(QtCore.QRect(10, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Login_button.setFont(font)
        self.Login_button.setObjectName("Login_button")
        self.Registration_button = QtWidgets.QPushButton(self.AuthWindow)
        self.Registration_button.setGeometry(QtCore.QRect(150, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Registration_button.setFont(font)
        self.Registration_button.setObjectName("Registration_button")
        self.lineEdit = QtWidgets.QLineEdit(self.AuthWindow)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.AuthWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 130, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.AuthWindow)
        self.label_3.setGeometry(QtCore.QRect(90, 15, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        A.setCentralWidget(self.AuthWindow)

        self.retranslateUi(A)
        QtCore.QMetaObject.connectSlotsByName(A)

    def retranslateUi(self, A):
        _translate = QtCore.QCoreApplication.translate
        A.setWindowTitle(_translate("A", "Авторизация"))
        self.label.setText(_translate("A", "Логин"))
        self.label_2.setText(_translate("A", "Пароль"))
        self.Login_button.setText(_translate("A", "Авторизация"))
        self.Registration_button.setText(_translate("A", "Регистрация"))
        self.lineEdit.setPlaceholderText(_translate("A", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("A", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    A = QtWidgets.QMainWindow()
    ui = Ui_A()
    ui.setupUi(A)
    A.show()
    sys.exit(app.exec_())
