# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(878, 469)
        self.centralwidget = QtWidgets.QWidget(Main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.worker_place = QtWidgets.QGroupBox(self.centralwidget)
        self.worker_place.setGeometry(QtCore.QRect(10, 10, 241, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.worker_place.setFont(font)
        self.worker_place.setObjectName("worker_place")
        self.Add_item = QtWidgets.QPushButton(self.worker_place)
        self.Add_item.setEnabled(False)
        self.Add_item.setGeometry(QtCore.QRect(10, 110, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add_item.setFont(font)
        self.Add_item.setObjectName("Add_item")
        self.Add_client = QtWidgets.QPushButton(self.worker_place)
        self.Add_client.setEnabled(True)
        self.Add_client.setGeometry(QtCore.QRect(10, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add_client.setFont(font)
        self.Add_client.setObjectName("Add_client")
        self.ref_but = QtWidgets.QPushButton(self.worker_place)
        self.ref_but.setEnabled(True)
        self.ref_but.setGeometry(QtCore.QRect(10, 380, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ref_but.setFont(font)
        self.ref_but.setObjectName("ref_but")
        self.Dell_client = QtWidgets.QPushButton(self.worker_place)
        self.Dell_client.setEnabled(False)
        self.Dell_client.setGeometry(QtCore.QRect(10, 290, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Dell_client.setFont(font)
        self.Dell_client.setObjectName("Dell_client")
        self.Add_client_2 = QtWidgets.QPushButton(self.worker_place)
        self.Add_client_2.setEnabled(False)
        self.Add_client_2.setGeometry(QtCore.QRect(10, 200, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add_client_2.setFont(font)
        self.Add_client_2.setObjectName("Add_client_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 10, 291, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 271, 421))
        self.listWidget.setObjectName("listWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 10, 301, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 281, 341))
        self.listWidget_2.setObjectName("listWidget_2")
        self.Exit_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Exit_button.setEnabled(True)
        self.Exit_button.setGeometry(QtCore.QRect(90, 380, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Exit_button.setFont(font)
        self.Exit_button.setObjectName("Exit_button")
        Main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "Рабочее окно сотрудника"))
        self.worker_place.setTitle(_translate("Main_window", "Сотрудник - "))
        self.Add_item.setText(_translate("Main_window", "Добавить имущество"))
        self.Add_client.setText(_translate("Main_window", "Добавить клиента"))
        self.ref_but.setText(_translate("Main_window", "Обновить списки"))
        self.Dell_client.setText(_translate("Main_window", "Удалить клиента"))
        self.Add_client_2.setText(_translate("Main_window", "Изменить данные "))
        self.groupBox.setTitle(_translate("Main_window", "Список клиентов"))
        self.groupBox_2.setTitle(_translate("Main_window", "Cписок имущества"))
        self.Exit_button.setText(_translate("Main_window", "Выход из программы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_window = QtWidgets.QMainWindow()
    ui = Ui_Main_window()
    ui.setupUi(Main_window)
    Main_window.show()
    sys.exit(app.exec_())
